// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://rovpdgnwjqfgevewxuwu.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdnBkZ253anFmZ2V2ZXd4dXd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTAxODMsImV4cCI6MjA2ODA2NjE4M30.2rKaS5JnXW-p20gH4BQ1cmnBtcgWllCUBbph301fh-c';

export const supabase = createClient(supabaseUrl, supabaseKey);

// Ensure the client is properly configured and used in your project
// Example usage:
// const { data, error } = await supabase.from('users').select('*');

// Remove all policies to authorize all users
// Run this SQL in Supabase SQL Editor:
// ALTER TABLE teacher_assignments DISABLE ROW LEVEL SECURITY;
// ALTER TABLE users DISABLE ROW LEVEL SECURITY;
// ALTER TABLE evaluations DISABLE ROW LEVEL SECURITY;